theme: jekyll-theme-minimal
title: Drew Lesh - CIT281 - Project 4
description: Node.js REST API server, using Fastify with multiple verbs(GET, POST, PUT, DELETE). Break code into manageable modules, and practice manipulating static data/objects in Javascript
